name: base
channels:
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - bioconductor-deseq2=1.42.0
  - bioconductor-edger=4.0.2
  - bioconductor-metagenomeseq=1.43.0
  - r-base=4.3.2
  - r-matrixstats=1.2.0